sonar.projectKey=aosedge_aos_core_lib_cpp
sonar.organization=aosedge

sonar.sources=src/
sonar.exclusions=**/tests/**,\
  **/pkcs11/cryptoki/**,\
  **/crypto/mbedtls/drivers/**,\
  **/crypto/mbedtls/mbedtls_config.h,\
  **/crypto/mbedtls/pkcs11.h

sonar.tests=src/
sonar.test.inclusions=**/tests/**

sonar.coverage.exclusions=**/tests/**

sonar.ws.timeout=600
