name: Check formatting

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - develop
      - feature_*

jobs:
  formatting-check:
    name: Formatting Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run clang-format style check
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: "15"
          exclude-regex: src\/common\/crypto\/mbedtls\/drivers\/.*|mbedtls_config\.h|include\/aos\/common\/pkcs11\/cryptoki/.*

      - name: Run cmake-format style check
        run: |
          python -m pip install --upgrade pip
          pip install cmake_format
          find . \( \( -not -path '*/build/*' \) -name '*.cmake' -or -name 'CMakeLists.txt' \) \
            -exec cmake-format --check {} +;
